name: review_ai
description: "AI Food Review App"
publish_to: "none"
version: 1.0.5+9
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  # flutter_dotenv: ^5.1.0 # API 키가 서버로 이전되어 더 이상 사용하지 않음
  image_picker: ^1.1.2
  clarity_flutter: ^1.0.0

  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.2.0
  google_mobile_ads: ^5.1.0
  confetti: ^0.7.0
  device_info_plus: ^9.1.0 # 디바이스 정보 확인용
  package_info_plus: ^4.2.0 # 패키지 정보 확인용
  path_provider: ^2.1.3
  fl_chart: ^0.68.0
  connectivity_plus: ^6.0.0

  geocoding: ^2.2.1
  geolocator: ^12.0.0
  permission_handler: ^11.0.0
  url_launcher: ^6.2.5
  dio: ^5.7.0
  json_annotation: ^4.9.0
  in_app_review: ^2.0.10
  image: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"
  json_serializable: ^6.10.0
  build_runner: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    # - .env # API 키가 서버로 이전되어 더 이상 사용하지 않음
    - assets/images/
    - assets/images/categories/
    - icon/
  fonts:
    - family: SCDream
      fonts:
        - asset: assets/fonts/SCDream3.otf
          weight: 300
        - asset: assets/fonts/SCDream4.otf
          weight: 400
        - asset: assets/fonts/SCDream5.otf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon/app_icon.png"
